const fs = require("fs");
const snarkjs = require("snarkjs");

async function main() {
  const publicSignals = JSON.parse(fs.readFileSync("publicSignals.json"));
  const proof = JSON.parse(fs.readFileSync("proof.json"));

  // verification_key.json: the verification key generated by the prover
  const vKey = JSON.parse(fs.readFileSync("verification_key.json"));

  // Verify the proof
  const res = await snarkjs.groth16.verify(vKey, publicSignals, proof);

  if (res === true) {
    console.log("Verification OK");
  } else {
    console.log("Invalid proof");
  }

  return res;
}

main()
  .then(() => {
    console.log("done!");
    process.exit(0);
  })
  .catch(console.error);
